spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${POINT_DB_URL}
    username: ${POINT_DB_USERNAME}
    password: ${POINT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

client:
  user-service:
    url: ${USER_SERVICE_URL}
  api-gateway-service:
    url: ${API_GATEWAY_SERVICE_URL}

logging:
  level:
    root: INFO
    woobl0g.pointservice: INFO
  file:
    name: logs/point-service.log
    path: logs
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB