spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${GAME_DB_URL}
    username: ${GAME_DB_USERNAME}
    password: ${GAME_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

client:
  point-service:
    url: ${POINT_SERVICE_URL}
  api-gateway-service:
    url: ${API_GATEWAY_SERVICE_URL}

logging:
  level:
    root: INFO
    woobl0g.gameservice: INFO
  file:
    name: logs/game-service.log
    path: logs
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB