services:
  point-service:
    build: .
    container_name: woobl0g-point-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POINT_DB_URL=${POINT_DB_URL}
      - POINT_DB_USERNAME=${POINT_DB_USERNAME}
      - POINT_DB_PASSWORD=${POINT_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - API_GATEWAY_SERVICE_URL=${API_GATEWAY_SERVICE_URL}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped