spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

client:
  point-service:
    url: ${POINT_SERVICE_URL}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:900000}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:604800000}