spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/user-db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379

client:
  point-service:
    url: http://localhost:8082
  api-gateway-service:
    url: http://localhost:8000

jwt:
  secret-key: woo120-secret-1234-1234-1234-1234
  access-token-validity: 900000  # 30분
  refresh-token-validity: 604800000  # 7일

logging:
  level:
    root: INFO
    woobl0g.userservice: DEBUG