spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

client:
  point-service:
    url: ${POINT_SERVICE_URL}