spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${BOARD_DB_URL}
    username: ${BOARD_DB_USERNAME}
    password: ${BOARD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

client:
  user-service:
    url: ${USER_SERVICE_URL}
  point-service:
    url: ${POINT_SERVICE_URL}