services:
  board-service:
    build: .
    container_name: woobl0g-board-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - BOARD_DB_URL=${BOARD_DB_URL}
      - BOARD_DB_USERNAME=${BOARD_DB_USERNAME}
      - BOARD_DB_PASSWORD=${BOARD_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - POINT_SERVICE_URL=${POINT_SERVICE_URL}
      - API_GATEWAY_SERVICE_URL=${API_GATEWAY_SERVICE_URL}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
